# Generated by Django 4.0.2 on 2022-02-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
        ),
    ]
