# Generated by Django 4.0.2 on 2022-02-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_receita_categoria_id_alter_receita_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='categoria_id',
        ),
    ]
