# Generated by Django 4.0.2 on 2022-02-20 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0009_receita_categoria_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='categoria_id',
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receitas.categoria'),
        ),
    ]
