# Generated by Django 4.0.2 on 2022-02-20 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0010_remove_receita_categoria_id_alter_receita_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categoria',
            new_name='nome',
        ),
    ]
