# Generated by Django 4.0.2 on 2022-02-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0011_rename_nome_categoria_categoria_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nome_categoria',
        ),
    ]
