# Generated by Django 4.0.2 on 2022-02-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0016_categoria_alter_receita_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
